name: Deploy Native Swift to TestFlight

on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: macos-15 
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.app 

      - name: Build and Archive App
        run: |
          cd IOS/LIFTR/V1.0.0/LIFTR
          xcodebuild -project LIFTR.xcodeproj \
                     -scheme LIFTR \
                     -configuration Release \
                     -archivePath $PWD/build/App.xcarchive \
                     archive \
                     CODE_SIGNING_ALLOWED=NO
                     | grep -A 5 -E "error:|warning:|failed" || true

      - name: Export IPA File
        run: |
          cd IOS/LIFTR/V1.0.0/LIFTR
          xcodebuild -exportArchive \
                     -archivePath $PWD/build/App.xcarchive \
                     -exportPath $PWD/build/output \
                     -exportOptionsPlist ExportOptions.plist

      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v4
        with:
          app-path: 'IOS/LIFTR/V1.0.0/LIFTR/build/output/LIFTR.ipa'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
